### ISSUE TITLE
Question/Enhancement: Possibility to provide untransformed N0 values

### ISSUE THREAD

**Issue by zionlion77** [albgarre/biogrowth#7]
I think it would be great to have the option of providing the populations sizes as non-transformed values. i.e. not as logN0, but as N0. If there is a way to achieve that with the current functions (e.g. fit_growth()), I would love to know how.

**Comment by albgarre** [comment]
Sorry for the long term in responding, @zionlion77 . The notification went into my spam folder. 

Yes, you can estimate N0 with the current version. You just need to define the initial value of "N0" instead of "logN0". For instance, see this code chunk that I have modified from the example of `fit_growth()`:

```
my_data <- data.frame(time = c(0, 25, 50, 75, 100),  # Data for the fit
                      logN = c(2, 2.5, 7, 8, 8))

models <- list(primary = "Baranyi")  # Model definition 

known <- c()  # No parameter is fixed

start <- c(logNmax = 8, lambda = 25, N0 = 2, mu = .2)  # IMPORTANT: here we define "N0" instead of "logN0"

primary_fit <- fit_growth(my_data, models, start, known,  # Model fitting as usual
                          environment = "constant"
                          )
```

If now you look at the parameter estimates, the estimated values and standard errors are given on N0:

```
summary(primary_fit)
```

>Parameters:
              Estimate Std. Error t value Pr(>|t|)    
logNmax 8.000e+00  3.804e-05  210318 3.03e-06 ***
lambda  2.322e+01  6.186e-04   37541 1.70e-05 ***
N0      1.000e+02  1.239e-02    8074 7.88e-05 ***
mu      1.884e-01  4.079e-06   46200 1.38e-05 ***
>Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
>Residual standard error: 5.379e-05 on 1 degrees of freedom
>Parameter correlation:
           logNmax    lambda         N0       mu
logNmax  1.000e+00 -0.002758 -5.725e-05 -0.04176
lambda  -2.758e-03  1.000000  6.900e-01  0.74750
N0      -5.725e-05  0.690034  1.000e+00  0.24396
mu      -4.176e-02  0.747498  2.440e-01  1.00000
